services:
  app:
      build: .
      ports:
        - 8080:8080
      depends_on:
        - postgres
        - minio
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "54320:5432"
    env_file:
      - ./.env.postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_WAVE:-wave_db}
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
    env_file:
      - ./.env.minio
    environment:
      MINIO_ROOT_USER: "imageStorage"
      MINIO_ROOT_PASSWORD: "imageStorage"