services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./.env.minio
    environment:
      MINIO_ROOT_USER: "imageStorage"
      MINIO_ROOT_PASSWORD: "imageStorage"