services:
  app:
      build: .
      ports:
        - 8082:8082
      env_file:
        - ./.env.postgres
      depends_on:
        - postgres
        - minio
      restart: on-failure
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "54320:5432"
    env_file:
      - ./.env.postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_WAVE:-wave_db}
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9002:9001"
    env_file:
      - ./.env.minio
    environment:
      MINIO_CONSOLE_ADDRESS: ':9001'
      MINIO_ROOT_USER: "imageStorage"
      MINIO_ROOT_PASSWORD: "imageStorage"
  createbuckets:
    image: minio/mc
    depends_on:
        - minio
    entrypoint: >
          /bin/sh -c "
          /usr/bin/mc alias set myminio http://minio:9000 imageStorage imageStorage;
          /usr/bin/mc mb myminio/image;
          /usr/bin/mc mb myminio/file;
          /usr/bin/mc policy set public myminio/image;
          /usr/bin/mc policy set public myminio/file;
          exit 0;
          "
